FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

COPY src/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY . /app

CMD ["python", "src/test.py"]




