name: CD

on:
<<<<<<< HEAD
  workflow_dispatch:
=======
  push:
    branches:
      - master
>>>>>>> c7f4100d6eede2942900cdc4d645d75fabf2f76d

jobs:
  Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stage
        run: |
          docker-compose -f docker-compose-app.yaml up --build -d
        working-directory: .

      - name: Debugging info
        run: |
          echo "Check the logs of the container:"
          docker logs celldataset_web_1
          echo "Sleeping for 10 seconds for the application to initialize..."
          sleep 10

<<<<<<< HEAD
      - name: Check the application
        run: |
          curl -X POST http://localhost:8080/predict -F "image=@/data/images/test/Huh7_Phase_A12_1_00d00h00m_1.tif"

=======
>>>>>>> c7f4100d6eede2942900cdc4d645d75fabf2f76d
      - name: containers
        run: docker ps -a
        
      - name: directory
        run: ls -l data/images/test
        
      - name: Check the application
        run: |
          curl -X POST http://localhost:8080/predict -F "image=@data/images/test/Huh7_Phase_A12_1_00d00h00m_1.tif"

<<<<<<< HEAD

=======
>>>>>>> c7f4100d6eede2942900cdc4d645d75fabf2f76d
