name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run docker-compose for preparing data and training
        run: |
          docker-compose -f docker-compose-train.yaml build 
          docker-compose -f docker-compose-train.yaml up
        working-directory: .

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: training-results
          path: ./

#  Stage:
#    runs-on: ubuntu-latest
#    needs: Build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Check permissions
#        run: |
#          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
#          find $GITHUB_WORKSPACE -type d -exec chmod 755 {} \;
#          find $GITHUB_WORKSPACE -type f -exec chmod 644 {} \;
#
#      - name: Download artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: training-results
#          path: ./
#
#      - name: Stage
#        run: |
#          docker-compose -f docker-compose-app.yaml up --build -d
#        working-directory: .
#
#      - name: Debugging info
#        run: |
#          echo "Check the logs of the container:"
#          docker logs classification_panguin_dataset_web_1
#          echo "Sleeping for 10 seconds for the application to initialize..."
#          sleep 10
#
#      - name: Check the application
#        run: |
#          curl -X POST http://localhost:8080/predict \
#          -d "body_mass=4200" \
#          -d "culmen_depth=13.9" \
#          -d "culmen_length=45.5" \
#          -d "flipper_length=210" \
#          -d "female=1" \
#          -d "male=0" \
#          -d "biscoe=1" \
#          -d "dream=0" \
#          -d "torgersen=0"







