name: CICD

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run docker-compose for preparing data and training
        run: |
          docker-compose -f docker-compose-train.yaml build 
          docker-compose -f docker-compose-train.yaml up
        working-directory: .
        continue-on-error: false

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: training-results
          path: ./


  Stage:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stage
        run: |
          docker-compose -f docker-compose-app.yaml up --build -d
        working-directory: .

      - name: Debugging info
        run: |
          echo "Check the logs of the container:"
          docker logs celldataset_training_web_1
          echo "Sleeping for 10 seconds for the application to initialize..."
          sleep 10

      - name: Check the application
        run: |
          curl -X POST http://localhost:8080/predict -F "image=@/data/images/test/Huh7_Phase_A12_1_00d00h00m_1.tif"




